In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [2]:
test = pd.read_csv('Data/Emotions/test.txt',sep=";",header=None)
train = pd.read_csv('Data/Emotions/train.txt',sep=";",header=None)
val = pd.read_csv('Data/Emotions/val.txt',sep=";",header=None)

In [7]:
# Splitting X and Y
x_train = train.iloc[:,0] 
y_train = train.iloc[:,1] 

x_test = test.iloc[:,0] 
y_test = test.iloc[:,1] 

x_val = test.iloc[:,0] 
y_val = test.iloc[:,1] 

x_train,y_train = np.array(x_train),np.array(y_train)
x_test,y_test = np.array(x_test),np.array(y_test)
x_val,y_val = np.array(x_val),np.array(y_val)

print(x_train.shape,"|",y_train.shape)
print(x_test.shape,"|",y_test.shape)
print(x_val.shape,"|",y_val.shape)

(16000,) | (16000,)
(2000,) | (2000,)
(2000,) | (2000,)


In [14]:
print(train.iloc[:,1].value_counts())

int_y_train = []
int_y_test = []
int_y_val = []

for l in y_train:
    
    if l == "joy":        
        int_y_train.append(0)
        
    if l == "sadness":       
        int_y_train.append(1)            
    if l == "anger":      
        int_y_train.append(2)      
    if l == "fear":
        int_y_train.append(3)
    if l == "love":
        int_y_train.append(4)
    if l == "surprise":
        int_y_train.append(5)
        
        
for l in y_test:
    
    if l == "joy":        
        int_y_test.append(0)
        
    if l == "sadness":       
        int_y_test.append(1)            
    if l == "anger":      
        int_y_test.append(2)      
    if l == "fear":
        int_y_test.append(3)
    if l == "love":
        int_y_test.append(4)
    if l == "surprise":
        int_y_test.append(5)
        
for l in y_val:
    
    if l == "joy":        
        int_y_val.append(0)
        
    if l == "sadness":       
        int_y_val.append(1)            
    if l == "anger":      
        int_y_val.append(2)      
    if l == "fear":
        int_y_val.append(3)
    if l == "love":
        int_y_val.append(4)
    if l == "surprise":
        int_y_val.append(5)
        


        
int_y_train,int_y_test,int_y_val = np.array(int_y_train),np.array(int_y_test),np.array(int_y_val)
from sklearn import preprocessing
#from keras.utils import np_utils

le = preprocessing.LabelEncoder()
le.fit(int_y_train)

encoded_y_train = le.transform(int_y_train)
encoded_y_test = le.transform(int_y_test)
encoded_y_val = le.transform(int_y_val)

#encoded_y_train = np_utils.to_categorical(encoded_y_train)
#encoded_y_test = np_utils.to_categorical(encoded_y_test)
#encoded_y_val = np_utils.to_categorical(encoded_y_val)

print(encoded_y_train)

print(int_y_train[:10])

joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: 1, dtype: int64
[1 1 2 ... 0 2 1]
[1 1 2 4 2 1 5 3 0 4]


In [12]:
encoded_y_val

array([1, 1, 1, ..., 0, 0, 3])